export const menuDatabase = [
  {"drinks": [
    {"id":1,
     "name":"Bouncy Brionne Soda",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem1.jpg",
     "descript":"A refreshing soda inspired by Brionne dancing in the water. Enjoy the bouncy texture of the gummies.",
     "price":2.99,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":2,
     "name":"Eevee Latte",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem8.jpg",
     "descript":"A signature latte with a comforting flavor. Enjoy the cute latte art of Eevee! (Cafeine Free)",
     "price":0.99,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":3,
     "name":"Furret Roasted Tea Latte",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem11.jpg",
     "descript":"A crisp and refreshing roasted green tea latte with a Furret playing peek-a-boo on top! (Cafeine Free and subs in Cider for Tea)",
     "price":4.99,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":4,
     "name":"Hot Litwik Cocoa",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem15.jpg",
     "descript":"Hot cocoa, warm like a Litwick's flame, topped with yummy marshmallows. Fortunately, drinking it won't drain your life-force.",
     "price":1.49,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":5,
     "name":"Miltank Mix au Lait",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem16.jpg",
     "descript":"Fresh Moomoo Milk is used in this mix au lait. The sweet and tart flavor of the berries really stands out!",
     "price":5.49,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":6,
     "name":"Lilligant FLoral Tea",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem17.jpg",
     "descript":"Original blended tea. The soothing scent has calming benefits, just like the flower on Lilligant's head. (more like cider than tea)",
     "price":1.49,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":7,
     "name":"Nutty Buneary Frappe",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem19.jpg",
     "descript":"A refreshing frappé with cookies shaped like Buneary's ears. The combination of the sweet cream and toasted nuts is superb! (Cafeine Free)",
     "price":2.49,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":8,
     "name":"Poppin' Pachirisu Float",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem23.jpg",
     "descript":"A soda float that's zappy like Pachirisu's electricity! Only a pro can top it off with even more ice cream!",
     "price":1.99,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100},
     {"id":9,
     "name":"Teddiursa Iced Coffee",
     "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem30.jpg",
     "descript":"An iced coffee with donuts in the shape of Teddiursa's ears. The coffee ice cubes let you savor every last sip! (Cafeine Free)",
     "price":5.99,
     "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
     "cal":100}
  ]},
  {"sweets":[
    {"id":10,
    "name":"Burnt-Caramel Vulpix Sundae",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem2.jpg",
    "descript":"A sweet and bitter dessert that depicts the cuteness and beauty of Vulpix. It tastes as good as it looks.",
    "price":4.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":11,
    "name":"Decorated Alcremie Cupcakes",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem6.jpg",
    "descript":"These decorated cupcakes are as cute as Alcremie. Share the sweetness with others!",
    "price":7.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":12,
    "name":"Scorbunny Berry Sandwich",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem26.jpg",
    "descript":"A fluffy fruit sandwich filled with strawberries and cream. The Scorbunny design is sure to make you feel energized!",
    "price":2.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":13,
    "name":"Pikachu Fruit Flan",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem20.jpg",
    "descript":"A decadent fruit flan loaded with fruits. Pikachu's smile is too cute to share.",
    "price":2.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":14,
    "name":"Ribombee Chocolate Cake",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem25.jpg",
    "descript":"An elegant bittersweet chocolate cake decorated with gold leaf. The Pollen Puff-like chocolate truffle simply melts in your mouth.",
    "price":1.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":15,
    "name":"Swablu Shaved Ice",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem28.jpg",
    "descript":"Shaved ice shaped like a Swablu. Make sure you eat up before it melts!",
    "price":3.00,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":16,
    "name":"Sylveon Custard Slice",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem29.jpg",
    "descript":"A cute, flaky pastry shaped like Sylveon's bow. The light, buttery smell is divine!",
    "price":3.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":17,
    "name":"Rainbow Oricorio Popcorn",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem24.jpg",
    "descript":"Multicolored popcorn inspired by the different styles of Oricorio. You can enjoy a variety of flavors all at once!",
    "price":2.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":18,
    "name":"Mienfoo Macaroon Mix",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem35.jpg",
    "descript":"An assortment of crunchy macaroons with creamy centers. Enjoy a barage of small, simple, sugary goodness colored after Mienfoo and it's shiny alternate. (new item)",
    "price":3.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100}
  ]}  ,
  {"plates":[
    {"id":19,
    "name":"Cheesy Rowlet Pizza",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem3.jpg",
    "descript":"A Rowlet-shaped pizza with gooey, stretchy chhese that's simply irresistible. Enjoy it while it's hot!",
    "price":3.00,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":20,
    "name":"Chikorita Bruschetta",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem5.jpg",
    "descript":"Bruschetta topped with basil a la Chikorita. The three kinds of toppings represent Chikorita's evolution.",
    "price":3.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":21,
    "name":"Dugtrio Sandwich Trio",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem7.jpg",
    "descript":"A hearty sandwich set that even satisfies a Dugtrio. Enjoy the fresh tomatoes bursting with flavor!",
    "price":3.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":22,
    "name":"Eiscue Caprese Salad",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem9.jpg",
    "descript":"A cooling caprese salad like Eiscue. Drizzle a generous amount of olive oil and enjoy!",
    "price":3.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":23,
    "name":"Sneasel Burger with Pickles",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem27.jpg",
    "descript":"A colorful hamburger using a pickle as one of Sneasel's ears. Enjoy it with some fries and salad!",
    "price":4.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":24,
    "name":"Fluffy Eevee Pancakes",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem10.jpg",
    "descript":"The whipped cream (as fluffy as Eevee's fur!) is a huge hit. Pure delight until the very last bite.",
    "price":3.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":25,
    "name":"Yummy Yamper Pasta",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem32.jpg",
    "descript":"A pasta bolognese depicting a playful Yamper. This cute and yummy dish will surely delight your taste buds and heart!",
    "price":4.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":26,
    "name":"Combee Waffles with Honey",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem33.jpg",
    "descript":"Combee-inspired waffles drizzled with honey. This sweet delight goes well with cider!",
    "price":4.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":27,
    "name":"Null",
    "imgLink":"",
    "descript":"",
    "price":0,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":0}
  ]},
  {"entrées":[
    {"id":28,
    "name":"Cheesy Whimsicott Meatloaf",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem4.jpg",
    "descript":"Fluffy Whimsicott plays hide-and-seek in cheese. Drizzle an accompanied sauce if you like!",
    "price":5.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":29,
    "name":"Gossifleur Combo Plate",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem12.jpg",
    "descript":"A combo plate loaded with vegetables just like the vibrant colors of Gossifleur. Enjoy it with our homemade mayo!",
    "price":6.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":30,
    "name":"Grain a la Pumpkaboo",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem13.jpg",
    "descript":"A gratin as generously sized as a large Pumpkaboo. This will surely satisfy your hunger!",
    "price":8.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":31,
    "name":"Happy Snorlax Loco Moco",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem14.jpg",
    "descript":"A satisfying loco moco that will put a smile on Snorlax's face. It even comes with a cup of soup!",
    "price":8.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":32,
    "name":"Mimikyu Frightfu Feast",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem18.jpg",
    "descript":"A true feast topped with a Mimikyu shaped pie and served with a drink. What could be lurking beneath all that melted cheese?!",
    "price":9.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":33,
    "name":"Piquant Pikachu Curry",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem21.jpg",
    "descript":"A vegetable-loaded curry with a kick to it. Enjoy a big plate and fuel your energy with Pikachu's smile!",
    "price":8.99,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":34,
    "name":"Playful Pancham Fried Rice",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem22.jpg",
    "descript":"A fun dish inspired by Pancham! You can enjoy a variety of flavors with this fried rice meal.",
    "price":7.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":35,
    "name":"Torchic Rice over Omelet",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem31.jpg",
    "descript":"Rice served atop an omelet as fluffy as Torchic's feathers. It goes well with ketchup!",
    "price":6.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100},
    {"id":36,
    "name":"Piping Hot Slugma Stew",
    "imgLink":"../Images/Pokemon Cafe/All_Menu_Items/MenuItem34.jpg",
    "descript":"A creamy stew with assorted vegetables, meats, and potatoes. Isn't as hot as an actual Slugma, but leaves you with a similar warm, cozy feeling inside. (new item)",
    "price":7.49,
    "rating": "⭐ ⭐ ⭐ ⭐ ⭐",
    "cal":100}
  ]}
]
